# Loading Data - SVHN

### Load in MatLab matrices

In [9]:
import scipy.io
from sklearn.model_selection import train_test_split
import numpy as np

In [10]:
test_mat = scipy.io.loadmat('../data/data_svhn/test_32x32.mat')
train_mat = scipy.io.loadmat('../data/data_svhn/train_32x32.mat')
extra_mat = scipy.io.loadmat('../data/data_svhn/extra_32x32.mat')

### Get data from matrices

In [4]:
# Get 
x_test = test_mat.get('X')  #numpy arrays
y_test = test_mat.get('y')

x_train = train_mat.get('X')
y_train = train_mat.get('y')

x_extra = extra_mat.get('X')
y_extra = extra_mat.get('y')

In [5]:
x_extra.shape

(32, 32, 3, 531131)

In [6]:
x_train.shape

(32, 32, 3, 73257)

In [7]:
x_test.shape

(32, 32, 3, 26032)

### Reshape the matrices

[h,w,channels,samples] -> [samples,h,w,channels]

In [11]:
x_test = np.transpose(x_test, axes=(3,0,1,2))
x_train = np.transpose(x_train, axes=(3,0,1,2))
x_extra = np.transpose(x_extra, axes=(3,0,1,2))

In [12]:
x_train.shape

(73257, 32, 32, 3)

### Split validation data

In [13]:
# Split train data into train and validation gettting certain number of labels from each class
def train_val_split_count(x_train, y_train, size, seed):
    
    if seed != None:
        np.random.seed(seed)  # Set seed if it is stated.

    labels = set(y_train.flatten())  # Get label names
    n_labels = len(labels)  # Get number of labels

    x_val = []
    y_val = []
    split = []

    for i in labels:
        labels_i = np.where(y_train == i)[0]
        #np.random.seed(seed)
        samples = np.random.choice(labels_i, size)  # TODO: Check if enough labels in the class
        split.append(samples)

    split = np.array(split).flatten()
    print(split[:10])

    x_val = np.array(x_train[split])
    y_val = np.array(y_train[split])
    
    x_train = np.delete(x_train, split, axis=0)
    y_train = np.delete(y_train, split, axis=0)
    
    return (x_train, x_val, y_train, y_val)

In [14]:
x_train1, x_val1, y_train1, y_val1 = train_val_split_count(x_train, y_train, size = 200, seed = 333)

[43375  4994 51023 32153 39898 29024 43722 18435 45000 54415]


In [15]:
print(x_train1.shape)
print(y_train1.shape)
print(x_val1.shape)
print(y_val1.shape)

(71280, 32, 32, 3)
(71280, 1)
(2000, 32, 32, 3)
(2000, 1)


In [16]:
x_extra2, x_val2, y_extra2, y_val2 = train_val_split_count(x_extra, y_extra, size = 400, seed = 333)

[432553 178960 197836 131442 524675 416661 144427 212716 381479  59914]


In [17]:
print(x_extra.shape)
print(y_extra2.shape)
print(x_val2.shape)
print(y_val2.shape)

(531131, 32, 32, 3)
(527153, 1)
(4000, 32, 32, 3)
(4000, 1)


In [18]:
from collections import Counter

Counter(list(y_val_all.flatten()))

NameError: name 'y_val_all' is not defined

### Add together train and extra data

In [19]:
x_train_all = np.concatenate([x_train1, x_extra2])
y_train_all = np.concatenate([y_train1, y_extra2])

In [20]:
x_val_all = np.concatenate([x_val1, x_val2])
y_val_all = np.concatenate([y_val1, y_val2])

In [21]:
x_train_all.shape

(598433, 32, 32, 3)

In [22]:
y_val_all.shape

(6000, 1)

### Load from script

In [1]:
from load_data_svhn import load_data_svhn

In [2]:
(x_train, y_train), (x_val, y_val), (x_test, y_test) = load_data_svhn()

In [3]:
print(x_train.shape)
print(y_train.shape)

print(x_val.shape)
print(y_val.shape)

print(x_test.shape)
print(y_test.shape)

(598431, 32, 32, 3)
(598431, 1)
(6000, 32, 32, 3)
(6000, 1)
(26032, 32, 32, 3)
(26032, 1)


In [4]:
data_mean = x_train.mean(axis=(0,1,2))
data_std = x_train.std(axis=(0,1,2))

MemoryError: 

In [5]:
data_mean

array([ 109.87035133,  109.69455486,  113.79160211])

In [6]:
data_std

NameError: name 'data_std' is not defined